# Generated by Django 4.2.5 on 2023-11-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login",
            field=models.CharField(
                default="asd", max_length=100, unique=True, verbose_name="login"
            ),
            preserve_default=False,
        ),
    ]
