# Generated by Django 4.2.5 on 2023-11-18 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="construction_object_guid",
            new_name="construction_object",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="counterparty_guid",
            new_name="counterparty",
        ),
    ]
