# Generated by Django 4.2.5 on 2023-11-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_confirm',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('accepted', 'принята'), ('cancelled', 'отменена'), ('on_confirm', 'на согласовании')], default='created', max_length=100),
        ),
    ]
