# Generated by Django 4.2.5 on 2023-11-18 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0002_rename_construction_object_guid_order_construction_object_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="construction_object",
            new_name="construction_object_guid",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="counterparty",
            new_name="counterparty_guid",
        ),
    ]
