# Generated by Django 4.2.5 on 2023-11-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0003_rename_construction_object_order_construction_object_guid_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создана"),
                    ("accepted", "принята"),
                    ("cancelled", "отменена"),
                ],
                max_length=100,
            ),
        ),
    ]
